### ISSUE TITLE
Bug with microprofile-health

### ISSUE THREAD

**Issue by cchet** [AdrianFarmadin/todo-jsf-example#1]
There seems to be a bug when microprofile-health dependency is added. I think its this issue hitting us https://issues.jboss.org/browse/THORN-2015.

We have already the fix in one of our company projects, which i will add soon.

**Comment by cchet** [comment]
@AdrianFarmadin 
I have updated to thorntail.io 2.1.9.Final, where the fixed the microprofile-config issue and many others.
Tested it locally, so please rebuild the Docker Image and push it to Docker Hub

**Comment by AdrianFarmadin** [comment]
Docker image rebuilded und pushed to DockerHub
